name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: lts
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: lts
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn lint
